// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prema.ChamaOne.Api.Backend.Database;

#nullable disable

namespace Prema.ChamaOne.Api.Backend.Migrations
{
    [DbContext(typeof(ChamaOneDatabaseContext))]
    partial class ChamaOneDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Contribution", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("fk_contribution_status_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_member_id")
                        .HasColumnType("int");

                    b.Property<decimal>("penalty")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.HasIndex("fk_contribution_status_id");

                    b.HasIndex("fk_member_id");

                    b.ToTable("contribution");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.ContributionStatus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("contribution_status");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Paid"
                        },
                        new
                        {
                            id = 2,
                            name = "Pending"
                        },
                        new
                        {
                            id = 3,
                            name = "Overdue"
                        });
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Gender", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("gender");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Male"
                        },
                        new
                        {
                            id = 2,
                            name = "Female"
                        });
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Loan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("fk_member_id")
                        .HasColumnType("int");

                    b.Property<decimal>("interest")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("interest_rate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("penalty")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("principal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.HasIndex("fk_member_id");

                    b.ToTable("loan");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Location.County", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("county");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Location.Subcounty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("fk_county_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("fk_county_id");

                    b.ToTable("subcounty");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Location.Ward", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("fk_subcounty_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("fk_subcounty_id");

                    b.ToTable("ward");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Member", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("fk_gender_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_member_type_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_residence_location_id")
                        .HasColumnType("int");

                    b.Property<string>("national_id_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("other_names")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("fk_gender_id");

                    b.HasIndex("fk_member_type_id");

                    b.HasIndex("fk_residence_location_id");

                    b.ToTable("member");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.MemberType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("member_type");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Member"
                        },
                        new
                        {
                            id = 2,
                            name = "Director"
                        },
                        new
                        {
                            id = 3,
                            name = "Deputy Director"
                        },
                        new
                        {
                            id = 4,
                            name = "Secratary"
                        },
                        new
                        {
                            id = 5,
                            name = "Deputy Secratary"
                        },
                        new
                        {
                            id = 6,
                            name = "Treasurer"
                        });
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("date_of_transaction")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("fk_transaction_entity_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_transaction_entity_type_id")
                        .HasColumnType("int");

                    b.Property<int>("fk_transaction_type_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("fk_transaction_entity_id");

                    b.HasIndex("fk_transaction_entity_type_id");

                    b.HasIndex("fk_transaction_type_id");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.TransactionEntityType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("transaction_entity_type");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Contribution"
                        },
                        new
                        {
                            id = 2,
                            name = "Loan"
                        },
                        new
                        {
                            id = 3,
                            name = "Project"
                        },
                        new
                        {
                            id = 4,
                            name = "Welfare"
                        });
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.TransactionType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("transaction_type");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Contribution Payment"
                        },
                        new
                        {
                            id = 2,
                            name = "Loan Disbursement"
                        },
                        new
                        {
                            id = 3,
                            name = "Loan Payment"
                        },
                        new
                        {
                            id = 4,
                            name = "Project Expense"
                        },
                        new
                        {
                            id = 5,
                            name = "Project Income"
                        },
                        new
                        {
                            id = 6,
                            name = "Welfare Disbursement"
                        });
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Contribution", b =>
                {
                    b.HasOne("Prema.ChamaOne.Api.Backend.Models.ContributionStatus", "ContributionStatus")
                        .WithMany("Contributions")
                        .HasForeignKey("fk_contribution_status_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.ChamaOne.Api.Backend.Models.Member", "Member")
                        .WithMany("Contributions")
                        .HasForeignKey("fk_member_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContributionStatus");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Loan", b =>
                {
                    b.HasOne("Prema.ChamaOne.Api.Backend.Models.Member", "Member")
                        .WithMany("Loans")
                        .HasForeignKey("fk_member_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Location.Subcounty", b =>
                {
                    b.HasOne("Prema.ChamaOne.Api.Backend.Models.Location.County", "County")
                        .WithMany("Subcounties")
                        .HasForeignKey("fk_county_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("County");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Location.Ward", b =>
                {
                    b.HasOne("Prema.ChamaOne.Api.Backend.Models.Location.Subcounty", "Subcounty")
                        .WithMany("Wards")
                        .HasForeignKey("fk_subcounty_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcounty");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Member", b =>
                {
                    b.HasOne("Prema.ChamaOne.Api.Backend.Models.Gender", "Gender")
                        .WithMany("Members")
                        .HasForeignKey("fk_gender_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.ChamaOne.Api.Backend.Models.MemberType", "MemberType")
                        .WithMany("Members")
                        .HasForeignKey("fk_member_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.ChamaOne.Api.Backend.Models.Location.Ward", "Ward")
                        .WithMany("Members")
                        .HasForeignKey("fk_residence_location_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("MemberType");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Transaction", b =>
                {
                    b.HasOne("Prema.ChamaOne.Api.Backend.Models.Contribution", "Contribution")
                        .WithMany("Transactions")
                        .HasForeignKey("fk_transaction_entity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.ChamaOne.Api.Backend.Models.Loan", "Loan")
                        .WithMany("Transactions")
                        .HasForeignKey("fk_transaction_entity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.ChamaOne.Api.Backend.Models.TransactionEntityType", "TransactionEntityType")
                        .WithMany("Transactions")
                        .HasForeignKey("fk_transaction_entity_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.ChamaOne.Api.Backend.Models.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("fk_transaction_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribution");

                    b.Navigation("Loan");

                    b.Navigation("TransactionEntityType");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Contribution", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.ContributionStatus", b =>
                {
                    b.Navigation("Contributions");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Gender", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Loan", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Location.County", b =>
                {
                    b.Navigation("Subcounties");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Location.Subcounty", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Location.Ward", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.Member", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.MemberType", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.TransactionEntityType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Prema.ChamaOne.Api.Backend.Models.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
