name: Backend - Build and Push Docker Image to Docker Hub
on:
  push:
    branches:
      - master
    paths:
      - 'Prema.ChamaOne.Api.Backend/**'  # This will watch for changes in the Backend directory
  workflow_dispatch:
jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4
      - name: build and push the image
        run: |
          docker login --username enockkim --password ${{ secret.GCR_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/enockkim/Prema.ChamaOne.Backend:latest
          docker push ghcr.io/enockkim/Prema.ChamaOne.Backend:latest
            
